dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  - "10"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  yarn: true

install: yarn

script: yarn test --karam-config karma.conf.js
